<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title></title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="site_libs/highlight/textmate.css"
      type="text/css" />
<script src="site_libs/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>

<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script src="site_libs/navigation-1.0/tabsets.js"></script>
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.9em;
  padding-left: 5px;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Course home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Course information
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="index.html">Course home</a>
    </li>
    <li>
      <a href="syllabus.html">Course Syllabus</a>
    </li>
    <li>
      <a href="course-overview.html">Course Overview</a>
    </li>
    <li>
      <a href="final-project.html">About final project</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Classes
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Class-01.html">Class 1: Introduction to decision making</a>
    </li>
    <li>
      <a href="Class-02.html">Class 2: The PrOACT Process</a>
    </li>
    <li>
      <a href="Class-03.html">Class 3: Uncertainty and decision making</a>
    </li>
    <li>
      <a href="Class-04.html">Class 4: Decision trees and nets</a>
    </li>
    <li>
      <a href="Class-05.html">Class 5: Intro to SDM and ARM</a>
    </li>
    <li>
      <a href="Class-06.html">Class 6: Structuring and quantifying objectives</a>
    </li>
    <li>
      <a href="Class-07.html">Class 7: Structuring objectives</a>
    </li>
    <li>
      <a href="Class-08.html">Class 8: Intro to R</a>
    </li>
    <li>
      <a href="Class-09.html">Class 9: Linear Models</a>
    </li>
    <li>
      <a href="Class-10.html">Class 10: LMs and GLMs</a>
    </li>
    <li>
      <a href="Class-11.html">Class 11: Prediction and GLMs</a>
    </li>
    <li>
      <a href="Class-12.html">Class 12: GLMs continued</a>
    </li>
    <li>
      <a href="Class-13.html">Class 13: Poissons</a>
    </li>
    <li>
      <a href="Class-14.html">Class 14: HLMs</a>
    </li>
    <li>
      <a href="Class-15.html">Class 15: HLMs and occupancy</a>
    </li>
    <li>
      <a href="Class-16.html">Class 16: Occupancy continued</a>
    </li>
    <li>
      <a href="Class-17.html">Class 17: Influence diagrams, Sensitivity analyses &amp; N-Mixtures</a>
    </li>
    <li>
      <a href="Class-18.html">Class 18: N-Mixtures &amp; Estimating abundance</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Assignments
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="hw-01.html">Homework 1</a>
    </li>
    <li>
      <a href="hw-02.html">Homework 2</a>
    </li>
    <li>
      <a href="hw-03.html">Homework 3</a>
    </li>
    <li>
      <a href="hw-04.html">Homework 4</a>
    </li>
    <li>
      <a href="hw-05.html">Homework 5</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Additional Resources
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="R-tutorials.html">R tutorials</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">




</div>


<p><!--


source("_build.R")
build("Class-17",bld="PAGE",docs=FALSE) # bld = PAGE,ENTIRE,SCRIPT

# PURL THIS SHIT & MOVE FILES TO DOCS
build("Class-17",bld="SCRIPT",docs=TRUE) # bld = PAGE,ENTIRE,SCRIPT

build("Class-17",bld="PAGE",docs=TRUE) # bld = PAGE,ENTIRE,SCRIPT

--></p>
<p><img src="media/banner-03.jpg" width="100%" /></p>
<div id="class-17-influence-diagrams-n-mixture-models" class="section level1 unnumbered">
<h1>Class 17: Influence diagrams &amp; N-Mixture models</h1>
</div>
<div id="class-preliminaries" class="section level1">
<h1><span class="header-section-number">1</span> Class preliminaries</h1>
<ul>
<li>Supplemental background reading for next class(es):
<ul>
<li>Conroy and Peterson Chapter 6 and 7.</li>
<li>Powell and Gale Chapter 17.</li>
</ul></li>
<li>Assignment due: None</li>
<li>Class project:
<ul>
<li>Be developing your decision model</li>
<li>Final exam period-April 28th at 3pm.</li>
</ul></li>
<li>Link to class recording <a href="">YouTube</a></li>
<li>Today’s R script <a href="scripts/Class-17.R">Class-17.R</a></li>
</ul>
<div id="class-overview-objectives" class="section level2">
<h2><span class="header-section-number">1.1</span> Class overview &amp; objectives</h2>
<ol style="list-style-type: decimal">
<li>Review final project</li>
<li>Review decision models
<ol style="list-style-type: decimal">
<li>Influence models</li>
<li>Sensitivity analysis</li>
<li>Response profiles</li>
</ol></li>
<li>Estimating abundance: <em>N</em>-Mixture models</li>
</ol>
</div>
<div id="getting-ready-to-go" class="section level2">
<h2><span class="header-section-number">1.2</span> Getting ready to go</h2>
<ul>
<li>The R scipt for class can be found <a href="scripts/Class-17.R">here</a></li>
<li>Once you have the script where you want it it where you want open the R script and be sure to check the working directory <code>getwd()</code> and make sure it is where your folder is.</li>
<li>If your working directory is not correct, you can set it in Rstudio: “Session –&gt; Set Working Directory –&gt; To source file location”. Or you can use the <code>setwd()</code> in the console</li>
<li>The data used today can be downloaded here <a href="study-area.Rdata">Rdata</a></li>
<li>You will want to install the following packages</li>
</ul>
<pre class="r"><code>#install.packages(&quot;reshape2&quot;)
#install.packages(&quot;unmarked&quot;)
#install.packages(&quot;fields&quot;)</code></pre>
</div>
</div>
<div id="n-mixture-models" class="section level1">
<h1><span class="header-section-number">2</span> N-Mixture models</h1>
<div id="overview" class="section level2">
<h2><span class="header-section-number">2.1</span> Overview</h2>
<p>Traditionally metrics like catch per unit effort (CPUE) would be used for comparisons (i.e., is cpue higher in one habitat relative to another). Comparing CPUE requires many assumptions as it relates to catchability (<span class="math inline">\(q\)</span>), where Catch is <span class="math inline">\(C = q\cdot f \cdot abundance\)</span>. Recent advances in <em>N</em>-mixture models relaxes this assumption by estimating capture probability for each site. One thing to note is that capture probability and catchability are not the same thing. Caveats aside the <em>N</em>-mixture provides a method to estimate density, accounting for imperfect capture. The gist of the approach is to repeatedly sample a site. The number of critters captured is a function of the underlying density and capture probability. For example if there were 100 critters at a site and your gear had a capture probability of 0.8 and then you sampled that site 5 times, you would expect to capture approximately 80 critters each time. In reality the data might look like this: 81 74 85 82 70,this is essentially a capture history but with counts instead of 0s and 1s. Because there was temporal replicates one can estimated a capture probability.</p>
<p>As it relates to habitat, the model may give the ability to estimate the density of hard to capture critters and the ability to compare among habitats. The design is not that different from what would occur for typical fishery or wildlife surveys, sample sites are randomly selected within an habitat and then repeated sampling is conducted to get the count history.</p>
</div>
<div id="application-to-estimating-abundance" class="section level2">
<h2><span class="header-section-number">2.2</span> Application to estimating abundance</h2>
<div id="what-a-hypothetical-irc-might-look-like" class="section level3">
<h3><span class="header-section-number">2.2.1</span> What a hypothetical IRC might look like</h3>
<p>Suppose there is an area with a spatial domain, study area, that looks like the image below. The blue represents depth (darker = deeper).</p>
<pre class="r"><code>load(&quot;study-area.Rdata&quot;)
library(fields)</code></pre>
<pre><code>## Warning: package &#39;fields&#39; was built under R version 3.1.3</code></pre>
<pre><code>## Loading required package: spam</code></pre>
<pre><code>## Warning: package &#39;spam&#39; was built under R version 3.1.3</code></pre>
<pre><code>## Loading required package: grid</code></pre>
<pre><code>## Spam version 1.3-0 (2015-10-24) is loaded.
## Type &#39;help( Spam)&#39; or &#39;demo( spam)&#39; for a short introduction 
## and overview of this package.
## Help for individual functions is also obtained by adding the
## suffix &#39;.spam&#39; to the function name, e.g. &#39;help( chol.spam)&#39;.</code></pre>
<pre><code>## 
## Attaching package: &#39;spam&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     backsolve, forwardsolve</code></pre>
<pre><code>## Loading required package: maps</code></pre>
<pre><code>## Warning: package &#39;maps&#39; was built under R version 3.1.3</code></pre>
<pre><code>## 
##  # maps v3.1: updated &#39;world&#39;: all lakes moved to separate new #
##  # &#39;lakes&#39; database. Type &#39;?world&#39; or &#39;news(package=&quot;maps&quot;)&#39;.  #</code></pre>
<pre class="r"><code>library(reshape2)</code></pre>
<pre><code>## Warning: package &#39;reshape2&#39; was built under R version 3.1.3</code></pre>
<pre class="r"><code>image.plot(x,y,z,xlim=c(0,7),
    xlab=&quot;X&quot;,ylab=&quot;Y&quot;,
    ylim=c(0,9), 
    col=rainbow(n=20,start=3/6,end=4/6),
    asp=1)  </code></pre>
<p><img src="Class-17_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Suppose that within the polygon above the true density of critters is 4<br />
per square meter (i.e., <span class="math inline">\(\lambda = 4\)</span> in <em>N</em>-mixture jargon). Applying that density to the polygon, the one realization of teh density of critters may look like the figure below. Recall we are using rpois so this is one stochastic realization.</p>
<p><img src="Class-17_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Using the framework, a survey can sample sites within the habitat. Suppose 20 randomly selected sites were used. That would look like the image below.</p>
<p><img src="Class-17_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
</div>
<div id="estimating-abundance" class="section level2">
<h2><span class="header-section-number">2.3</span> Estimating abundance</h2>
<p>Using the 20 samples abundance can be estimated using an <em>N</em>-mixture model, given some assumptions. Variables estimated by the <em>N</em>-mixture model are:</p>
<ul>
<li><span class="math inline">\(\lambda\)</span> is initial population density</li>
<li><span class="math inline">\(p\)</span> is capture probability</li>
</ul>
<p>Specifically the process model is:</p>
<p><span class="math display">\[N_{i} \sim Poisson(\lambda)\]</span></p>
<p>and</p>
<p><span class="math display">\[y_{i,k}~binomial(N_{i},p)\]</span></p>
<p>and</p>
<p><span class="math display">\[log(\lambda) = \beta_0\]</span></p>
<p>and</p>
<p><span class="math display">\[logit(\p) = \gamma_0\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(N_{i}\)</span> is the predicted count,<br />
</li>
<li><span class="math inline">\(\lambda\)</span> is the underlying density,<br />
</li>
<li><span class="math inline">\(y_{i,t}\)</span> is the number of critters observed at site <span class="math inline">\(i\)</span> at time <span class="math inline">\(t\)</span>,<br />
</li>
<li><span class="math inline">\(p\)</span> is capture probability,<br />
</li>
<li><span class="math inline">\(i\)</span> indexes each randomly selected site,<br />
</li>
<li><span class="math inline">\(k\)</span> indexes each visit,<br />
</li>
<li><span class="math inline">\(\beta_0\)</span> is the intercept of the linear model predicting the log abundance, and<br />
</li>
<li><span class="math inline">\(\gamma_0\)</span> is the intercept of the linear model predicting the log odds of capture probability.</li>
</ul>
<p>The assumptions for the model above included:</p>
<ul>
<li>Counts are independent among site <span class="math inline">\(i\)</span> and visit <span class="math inline">\(k\)</span>,</li>
<li>Capture probability is homogenous, and</li>
<li><span class="math inline">\(N\)</span> is the true underlying count at site <span class="math inline">\(i\)</span></li>
<li>Populations closed between surveys</li>
</ul>
<div id="no-covariates-lambda-and-p-homogenous" class="section level3">
<h3><span class="header-section-number">2.3.1</span> No covariates: <span class="math inline">\(\lambda\)</span> and <span class="math inline">\(p\)</span> homogenous</h3>
<p>The sampling design in the plot above illustrates how the design might play out in an IRC habitat. Each site would be visited 2 or more times either within a day or within a time period that is sufficiently short, such that demographic closure can be assumed. The process assumes temporal replicates, however spatial replicates have been used with occupancy models, so it is suggestive that it might work for <em>N</em>-mixture models. This first analysis assumes there is no underlying relationship with abiotic or biotic covariates such as depth on abundance or capture probability, i.e., density arises from a Poisson process.</p>
<p>The code below generates catches at 20 sites over 5 occasions given the abundance at the site and a capture probability (<span class="math inline">\(p\)</span>) = 0.4.</p>
<pre class="r"><code>nsamples&lt;- 50 # i = 1,2,3,...20
beta_0&lt;- 1.386 # UNDERLYING DENSITY
gamma_0&lt;- -0.405 # LOG ODDS CAPTURE PROBABILITY

# TRANSFORM TO REAL VALUES
lambda &lt;- exp(beta_0)
lambda</code></pre>
<pre><code>## [1] 3.998823</code></pre>
<pre class="r"><code>p&lt;- exp(gamma_0)/(1+exp(gamma_0) )
p</code></pre>
<pre><code>## [1] 0.4001116</code></pre>
<pre class="r"><code># SIMULATE ABUNDANCES 
set.seed(1985)# FOR REPRODUCABILITY; LAST YEAR DLR WAS IN VAN HALEN
sa$N&lt;- rpois(nrow(sa),lambda)

# GENERATE CAPTURE HISTORIES
visits&lt;-5 # k = 1,2,3,4,5
# MATRIX TO HOLD VALUES
y&lt;- matrix(0,nrow(sa),visits) # matrix for all possible sites
for(i in 1:nrow(sa))
    {
    for(k in 1:visits)
        {
        y[i,k]&lt;- rbinom(1,sa$N[i],p)#obs count for visit k and site i
        }
    }</code></pre>
<p>The simulated counts at each of the 50 sites for 5 visits is shown below.</p>
<pre class="r"><code>sample_indx&lt;- sample(1:nrow(sa),nsamples,replace=FALSE)
obs&lt;- y[sample_indx,]
obs</code></pre>
<pre><code>##       [,1] [,2] [,3] [,4] [,5]
##  [1,]    1    1    3    2    3
##  [2,]    0    1    0    2    1
##  [3,]    1    2    1    0    1
##  [4,]    1    2    1    2    2
##  [5,]    1    0    1    0    0
##  [6,]    1    0    1    1    2
##  [7,]    1    1    1    0    1
##  [8,]    1    1    2    1    1
##  [9,]    5    2    3    4    5
## [10,]    3    3    0    2    2
## [11,]    1    1    3    2    1
## [12,]    3    3    2    2    2
## [13,]    3    4    5    4    3
## [14,]    3    3    1    0    2
## [15,]    3    3    3    2    2
## [16,]    0    4    3    2    3
## [17,]    0    1    0    0    1
## [18,]    1    2    2    1    0
## [19,]    1    2    1    1    3
## [20,]    2    2    0    2    3
## [21,]    3    0    3    1    0
## [22,]    1    0    1    3    2
## [23,]    2    0    2    4    1
## [24,]    2    4    4    1    2
## [25,]    1    2    1    0    1
## [26,]    3    3    3    2    1
## [27,]    3    1    1    2    1
## [28,]    2    0    2    3    0
## [29,]    2    3    1    4    1
## [30,]    3    2    1    1    1
## [31,]    2    2    3    3    1
## [32,]    1    2    1    2    0
## [33,]    2    1    3    1    1
## [34,]    0    1    2    1    0
## [35,]    2    0    2    0    2
## [36,]    1    1    2    1    1
## [37,]    2    2    2    3    2
## [38,]    1    2    1    2    1
## [39,]    0    3    2    1    1
## [40,]    3    1    3    2    1
## [41,]    0    1    1    2    0
## [42,]    2    3    2    4    4
## [43,]    2    0    1    2    1
## [44,]    2    1    1    1    1
## [45,]    0    1    2    1    1
## [46,]    1    1    1    1    0
## [47,]    3    4    3    5    2
## [48,]    0    1    0    0    2
## [49,]    3    2    3    0    3
## [50,]    1    2    1    1    1</code></pre>
<p>The data in the table above is then used to estimate <span class="math inline">\(\lambda\)</span> and <span class="math inline">\(p\)</span> using the <em>N</em>-mixture model. This is done using the <code>pcount()</code> function from the <code>unmarked</code> library. Note there was some manipulation of the data using the <code>unmarkedFramePCount()</code> function to process the input data prior to fitting the model.</p>
<pre class="r"><code># Prepare data
library(unmarked)</code></pre>
<pre><code>## Warning: package &#39;unmarked&#39; was built under R version 3.1.3</code></pre>
<pre><code>## Loading required package: reshape</code></pre>
<pre><code>## 
## Attaching package: &#39;reshape&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:reshape2&#39;:
## 
##     colsplit, melt, recast</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## Warning: package &#39;lattice&#39; was built under R version 3.1.3</code></pre>
<pre><code>## Loading required package: Rcpp</code></pre>
<pre><code>## Warning: package &#39;Rcpp&#39; was built under R version 3.1.3</code></pre>
<pre><code>## 
## Attaching package: &#39;unmarked&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:spam&#39;:
## 
##     mle</code></pre>
<pre class="r"><code>data &lt;- unmarkedFramePCount(y = y)

# ~DETECTION ~ ABUNDANCE
fit &lt;- pcount(~1 ~ 1, 
    data=data, 
    K=50) # SET THIS HIGHER THAN YOUR EXPECTED ABUNDANCE
summary(fit)</code></pre>
<pre><code>## 
## Call:
## pcount(formula = ~1 ~ 1, data = data, K = 50)
## 
## Abundance (log-scale):
##  Estimate     SE    z   P(&gt;|z|)
##      1.32 0.0407 32.5 3.38e-231
## 
## Detection (logit-scale):
##  Estimate     SE     z  P(&gt;|z|)
##    -0.345 0.0615 -5.62 1.94e-08
## 
## AIC: 7574.544 
## Number of sites: 524
## optim convergence code: 0
## optim iterations: 38 
## Bootstrap iterations: 0</code></pre>
<p>Once the model is fit and estimates are returned, the estimates are then back transformed from log and logit scale for abundance and capture probability respectively.</p>
<pre class="r"><code># Density
lambda</code></pre>
<pre><code>## [1] 3.998823</code></pre>
<pre class="r"><code>exp(coef(fit)[1]) # should be close to lambda</code></pre>
<pre><code>## lam(Int) 
## 3.752949</code></pre>
<pre class="r"><code># Capture probability
p</code></pre>
<pre><code>## [1] 0.4001116</code></pre>
<pre class="r"><code>exp(coef(fit)[2])/(1+exp(coef(fit)[2])) # should be close p</code></pre>
<pre><code>##    p(Int) 
## 0.4145342</code></pre>
<p>After fitting the <em>N</em>-mixture model the estimate of <span class="math inline">\(\lambda\)</span> was 3.75, recall that the value used to generate the data was 3.9988227 and the estimate of <span class="math inline">\(p\)</span> was 0.41, recall the that value used was 0.4001116. The estimates should be in the ballpark.</p>
<!--
need to clarify notation and notation within code
-->
</div>
<div id="covariates-for-lambda-and-p" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Covariates for <span class="math inline">\(\lambda\)</span> and <span class="math inline">\(p\)</span></h3>
<p>The no covariates for <span class="math inline">\(\lambda\)</span> and <span class="math inline">\(p\)</span> is a rather unrealistic condition in nature. This example shows how a biologically relevant metric like depth can be used to model abundance and capture probability. Note that this example assumes there is a true underlying relationship with the abundance and capture probability of the critter and depth. Recall the figure above of the hypothesized study area with varying depths. Suppose abundance was inversely related to depth within and study area and that relationship is illustrated below. Formally we change the equation predicting <span class="math inline">\(\lambda\)</span> to</p>
<p><span class="math display">\[log(\lambda) = \beta_0 + \beta_1 \cdot Depth\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(\lambda\)</span> is the underlying density,</li>
<li><span class="math inline">\(\beta_0\)</span> is the intercept of the linear model predicting the density, and<br />
</li>
<li><span class="math inline">\(\beta_1\)</span> is the effect of depth on abundance.</li>
</ul>
<p><img src="Class-17_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>The effect of depth on abundance within the study area is negative, indicating critter abundances are higher at lower depths. This underlying density relationship might look like the figure below where the expected density is</p>
<p><span class="math display">\[N \sim Poisson(exp(\beta_{0} + \beta_{1} \cdot depth))\]</span>,</p>
<p>where * <span class="math inline">\(\beta_{0} =\)</span> 3, and <span class="math inline">\(\beta_{1} =\)</span> -0.5.</p>
<p>The actual abundance for each site given the depth is simulated and illustrated below.</p>
<p><img src="Class-17_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Similarly, capture probability can be related to depth or some other environmental covariate. Suppose that capture probability was a function of depth, this might be the case when using a seine and it might be very difficult to fish the deep areas, just a hypothetical example here. This relationship might look like the figure below where the capture probability is</p>
<p><span class="math display">\[logit(p) = \gamma_{0} + \gamma_{1} \cdot depth\]</span>,</p>
<p>where</p>
<ul>
<li><span class="math inline">\(\beta_{0} =\)</span> 1, and</li>
<li><span class="math inline">\(\beta_{1} =\)</span> -0.5.</li>
</ul>
<p><img src="Class-17_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Using the relationship of <span class="math inline">\(p\)</span> and depth and the abundance at each site the capture histories can be generated accounting for site-specific depth and capture probability.</p>
<pre class="r"><code># GENERATE CAPTURE HISTORIES
visits&lt;-5
p&lt;- exp(gamma_0+gamma_1*sampleSites$depth)/
    (1+exp(gamma_0+gamma_1*sampleSites$depth))
y&lt;- matrix(0,nsamples,visits)
for(i in 1:nsamples)
    {
    y[i,]&lt;- rbinom(visits,sampleSites$abundance[i],p[i])
    }</code></pre>
<p>The simulated catch at each of the 40 sites for 5 occasions is shown below.</p>
<pre><code>##       [,1] [,2] [,3] [,4] [,5]
##  [1,]   16   14   16   11   13
##  [2,]    6    6    6    3    5
##  [3,]    5    7    3    6    5
##  [4,]    2    5    1    6    3
##  [5,]   12    9    7   11   11
##  [6,]    1    3    2    4    2
##  [7,]    4    4    3    2    2
##  [8,]    4    5    7    6    4
##  [9,]    1    0    3    1    2
## [10,]   12   13   12   15   14
## [11,]    5    4    5    4    6
## [12,]    2    0    0    1    1
## [13,]   17   16   18   20   15
## [14,]    1    0    1    0    1
## [15,]    3    1    1    1    3
## [16,]    7    7    8   10    7
## [17,]    4    2    2    3    1
## [18,]    2    4    4    2    2
## [19,]    1    1    2    1    1
## [20,]    6    4    4    4    4
## [21,]    3    4    4    3    4
## [22,]    7    4    4    3    2
## [23,]    3    1    2    3    0
## [24,]    1    0    1    0    0
## [25,]    2    3    3    2    1
## [26,]   19   18   17   18   19
## [27,]   18   20   20   17   15
## [28,]   14   13   15   18   17
## [29,]    1    2    4    3    3
## [30,]    5    4    2    2    1
## [31,]    1    0    2    0    1
## [32,]    2    3    2    3    4
## [33,]    5    6    4    5    5
## [34,]    5    9    9    5    7
## [35,]   10   13   10   11   12
## [36,]    4    5    3    4    2
## [37,]    3    3    4    1    1
## [38,]    4    2    2    0    1
## [39,]    3    5    4    5    5
## [40,]    0    1    3    2    1</code></pre>
<p>The model is fit as before, but with 4 estimates produce 2 intercepts and 2 betas for the the relationship of depth on <span class="math inline">\(\lambda\)</span> and <span class="math inline">\(p\)</span>.</p>
<pre class="r"><code># PREPARE DATA
data &lt;- unmarkedFramePCount(y = y,
    siteCovs=data.frame(depth=sampleSites$depth))
# FIT THE MODEL WITH DEPTH AS A COVARIATE FOR LAMBDA AND P
fit &lt;- pcount(~depth +1 ~depth+1, 
    data=data, 
    K=150)
fit</code></pre>
<pre><code>## 
## Call:
## pcount(formula = ~depth + 1 ~ depth + 1, data = data, K = 150)
## 
## Abundance:
##             Estimate     SE     z   P(&gt;|z|)
## (Intercept)     2.99 0.1194 25.04 1.99e-138
## depth          -0.46 0.0913 -5.04  4.74e-07
## 
## Detection:
##             Estimate    SE     z  P(&gt;|z|)
## (Intercept)    1.145 0.275  4.16 3.19e-05
## depth         -0.545 0.148 -3.69 2.24e-04
## 
## AIC: 743.9707</code></pre>
<p>After fitting the <em>N</em>-mixture model the estimate of <span class="math inline">\(\beta_{0}\)</span> and <span class="math inline">\(\beta_{1}\)</span> a was 2.99 and -0.46, recall that the value used to generate the data was 3 and -0.5 for the relationship of abundance with depth. The estimate of <span class="math inline">\(\beta_{0}\)</span> and <span class="math inline">\(\beta_{1}\)</span> for the function relating capture probability to depth was 1.15 and -0.54, recall the that value used was 1 and -0.5.</p>
<p>Ignoring uncertainties for the moment, we can estimate the total abundance given depth at each location in the study area as <span class="math inline">\(N = \sum_{i=1}^{I} exp(2.99 \cdot -0.46 \cdot depth_{i})\)</span>, where <span class="math inline">\(i\)</span> indexes each grid in the study area.</p>
<p>The image below illustrates the true abundances for a simulated study area and the estimated abundances.</p>
<p><img src="Class-17_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Using the predictions the estimate of abundance in the study area is 5522 and the true abundance was 5395. There are design aspects where fine tuning can occur, such as modifying the number of replicates to take or how many sites to sample and where to put them.</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
